# 자연어처리(Natural Language)
- 음성이나 텍스트를 컴퓨터가 인식하고 처리하는 것

# 1. 텍스트의 토큰화
- 토큰(token): 입력할 텍스트가 준비되면 이를 단어별, 문장별, 형태소별로 나눌 수 있는데 이렇게 작게 나누어진 하나의 단위

In [30]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# 전처리할 텍스트 정하기
text = '해보지 않으면 해낼 수 없다'

# 해당 텍스트를 토큰화
result = text_to_word_sequence(text)
print('\n원문:\n', text)
print('\n토큰화:\n', result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [31]:
from tensorflow.keras.preprocessing.text import Tokenizer

docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

In [32]:
token = Tokenizer() # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용

print('\n단어 카운트:\n', token.word_counts) # 단어의 빈도수를 계산한 결과 출력


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [33]:
print('\n문장 카운트: ', token.document_count) # 총 몇 개의 문장이 들어 있는지 세기


문장 카운트:  3


In [34]:
print('\n각 단어가 몇 개의 문장에 포함되어 있는가:\n', token.word_docs) # 각 단어들이 몇 개의 문장에 나오는지 세어서 출력


각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'먼저': 1, '토큰화합니다': 1, '단어를': 1, '각': 1, '나누어': 1, '텍스트의': 2, '딥러닝에서': 2, '토큰화해야': 1, '인식됩니다': 1, '단어로': 1, '토큰화한': 1, '결과는': 1, '있습니다': 1, '수': 1, '사용할': 1})


In [35]:
print('\n각 단어에 매겨진 인덱스 값:\n', token.word_index) # 각 단어에 매겨진 인덱스 값 출력


각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


# 2. 단어의 원-핫 인코딩

In [36]:
text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [37]:
# 원-핫 인코딩 방식으로 표현
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [38]:
from tensorflow.keras.utils import to_categorical

# 인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)

print(x)
# 오랫동안
# 꿈꾸는
# 이는
# 그
# 꿈을
# 닮아간다

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


# 3. 단어 임베딩
- 주어진 배열을 정해진 길이로 압축

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(16, 4)) # 총 단어수는 16, 벡터 크기는 4

# 4. 텍스트를 읽고 긍정, 부정 예측하기

In [48]:
import numpy as np

# 텍스트 리뷰 자료를 지정합니다.
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다.', '한번 더 보고싶네요',
       '글쎄요', '별로예요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정
classs = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [49]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index) # 토큰화된 결과를 출력해 확인

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [50]:
# 토큰에 지정된 인덱스로 새로운 배열 생성
x = token.texts_to_sequences(docs)
print('\n리뷰 텍스트, 토큰화 결과:\n', x)


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [51]:
# 패딩(padding): 길이를 똑같이 맞추어 주는 작업
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_x = pad_sequences(x, 4) # 서로 다른 길이의 데이터를 4로 맞추기
print('\n패딩 결과:\n', padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [52]:
# 전체 단어의 맨 앞에 0이 먼저 나와야 하므로 총 단어 수에 1을 더하는 것
word_size = len(token.word_index) + 1

In [53]:
# 패딩 과정을 거쳐 네 개의 길이로 맞추어 주었으므로 네 개의 단어가 들어가게 설정하면 임베딩 과정은 다음 한줄로 표현
Embedding(word_size, 8, input_length=4)

In [54]:
# 단어 임베딩을 포함해 딥러닝 모델을 만들고 결과를 출력
from tensorflow.keras.layers import Dense, Flatten

model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classs, epochs=20)
print('\n Accuracy: %.4f' % (model.evaluate(padded_x, classs)[1]))

Epoch 1/20
1/1 [==============================] - 1s 843ms/step - loss: 0.6881 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6857 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6833 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6808 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6784 - accuracy: 0.8000
Epoch 6/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6759 - accuracy: 0.9000
Epoch 7/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6735 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6711 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6686 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6662 - accuracy: 0.9000
Epoch 11/20
1/1 [=================

# 전체 코드: 영화 리뷰가 긍정적인지 부정적인지 예측

In [59]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical

import numpy as np

# 텍스트 리뷰 자료 지정
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다.', '한번 더 보고싶네요',
       '글쎄요', '별로예요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정
classes = np.array([1,1,1,1,1,0,0,0,0,0])

# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

x = token.texts_to_sequences(docs)
print('\n리뷰 텍스트, 토큰화 결과:\n', x)

# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.
padded_x = pad_sequences(x, 4)
print('\n패딩 결과:\n', padded_x)

# 임베딩에 입력될 단어의 수를 지정
word_size = len(token.word_index) + 1

# 단어 임베딩을 포함해 딥러닝 모델을 만들고 결과를 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classs, epochs=20)
print('\n Accuracy: %.4f' % (model.evaluate(padded_x, classs)[1]))

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]

패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]
Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_14 (Embedding)    (None, 4, 8)              168       
                                                                 
 flatten_8 (Flatten)         (None, 32)                0         
                                                                 
 dense_8 (Dense)             (None, 1)                 33        
                            